#!/bin/bash
DIR=${0%/*}
if [ -r $DIR/FWLoader.jar ]; then
    java -cp $DIR/FWLoader.jar FWLoader $@
else 
#    export CLASSPATH=$CLASSPATH:/usr/share/java/ztex.jar:/usr/local/share/java/ztex.jar:/usr/share/java/libusbJava.jar:/usr/local/share/java/libusbJava.jar:/usr/share/libusbJava:/usr/local/share/libusbJava
    export CLASSPATH=$CLASSPATH:/usr/local/share/java:/usr/share/java
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/lib
    java FWLoader $@
fi    
