VPATH += :$(HALPATH)/saml11
SRC += saml11_hal.c startup_saml11e16a.c system_saml11e16a.c
EXTRAINCDIRS += $(HALPATH)/saml11 $(HALPATH)/saml11/CMSIS

MCU_FLAGS = -mcpu=cortex-m23

CC = arm-none-eabi-gcc
OBJCOPY = arm-none-eabi-objcopy
OBJDUMP = arm-none-eabi-objdump
SIZE = arm-none-eabi-size
AR = arm-none-eabi-ar rcs
NM = arm-none-eabi-nm

#Output Format = Binary for this target
FORMAT = binary

CFLAGS += -fdata-sections -ffunction-sections -funsigned-char -funsigned-bitfields -mthumb -D_SAML11E16A -mlong-calls
CPPFLAGS += $(CFLAGS)
ASFLAGS += -mthumb

CDEFS += -D__SAML11E16A__
CPPDEFS += $(CDEFS)

LDFLAGS += -specs=nano.specs -specs=nosys.specs -T $(HALPATH)/saml11/saml11e16a_flash.ld -Wl,--gc-sections -lm
