# Makefile for CW308T-IMX1062 Target

VPATH += :$(HALPATH)/imxrt1062
VPATH += :$(HALPATH)/imxrt1062/nxp
VPATH += :$(HALPATH)/imxrt1062/nxp/board
VPATH += :$(HALPATH)/imxrt1062/nxp/component/uart
VPATH += :$(HALPATH)/imxrt1062/nxp/component/serial_manager
VPATH += :$(HALPATH)/imxrt1062/nxp/component/lists
VPATH += :$(HALPATH)/imxrt1062/nxp/device
VPATH += :$(HALPATH)/imxrt1062/nxp/drivers
VPATH += :$(HALPATH)/imxrt1062/nxp/source
VPATH += :$(HALPATH)/imxrt1062/nxp/startup
VPATH += :$(HALPATH)/imxrt1062/nxp/utilities
VPATH += :$(HALPATH)/imxrt1062/xip

EXTRAINCDIRS += $(HALPATH)/imxrt1062/nxp
EXTRAINCDIRS += $(HALPATH)/imxrt1062/nxp/board
EXTRAINCDIRS += $(HALPATH)/imxrt1062/nxp/CMSIS
EXTRAINCDIRS += $(HALPATH)/imxrt1062/nxp/component/uart
EXTRAINCDIRS += $(HALPATH)/imxrt1062/nxp/component/serial_manager
EXTRAINCDIRS += $(HALPATH)/imxrt1062/nxp/component/lists
EXTRAINCDIRS += $(HALPATH)/imxrt1062/nxp/device
EXTRAINCDIRS += $(HALPATH)/imxrt1062/nxp/drivers
EXTRAINCDIRS += $(HALPATH)/imxrt1062/nxp/source
EXTRAINCDIRS += $(HALPATH)/imxrt1062/nxp/startup
EXTRAINCDIRS += $(HALPATH)/imxrt1062/nxp/utilities
EXTRAINCDIRS += $(HALPATH)/imxrt1062/xip

SRC += board.c clock_config.c pin_mux.c
SRC += generic_list.c serial_manager.c serial_port_uart.c lpuart_adapter.c
SRC += system_MIMXRT1062.c
SRC += fsl_clock.c fsl_common.c fsl_gpio.c fsl_lpuart.c 
SRC += semihost_hardfault.c 
SRC += startup_mimxrt1062.c
SRC += fsl_assert.c fsl_debug_console.c fsl_str.c
SRC += imxrt1062_hal.c
SRC += evkmimxrt1060_flexspi_nor_config.c fsl_flexspi_nor_boot.c
SRC += fsl_dcp.c fsl_snvs_lp.c

MCU_FLAGS = -mcpu=cortex-m7 -mthumb -mfloat-abi=soft

CC = arm-none-eabi-gcc
OBJCOPY = arm-none-eabi-objcopy
OBJDUMP = arm-none-eabi-objdump
SIZE = arm-none-eabi-size
AR = arm-none-eabi-ar rcs
NM = arm-none-eabi-nm

#Output Format = Binary for this target
FORMAT = binary

CPPFLAGS += $(CFLAGS)
ASFLAGS += -mthumb

CDEFS += -DCPU_MIMXRT1062DVL6A -DCPU_MIMXRT1062DVL6A_cm7 -DSDK_DEBUGCONSOLE=1
CDEFS += -DXIP_EXTERNAL_FLASH=1 -DXIP_BOOT_HEADER_ENABLE=1 -DSERIAL_PORT_TYPE_UART=1
CDEFS += -DCR_INTEGER_PRINTF -DPRINTF_FLOAT_ENABLE=0 -D__MCUXPRESSO -D__USE_CMSIS -DDEBUG 

CPPDEFS += $(CDEFS)

# -D__REDLIB__
# redlib.specs

LDFLAGS += -specs=nosys.specs -T $(HALPATH)/imxrt1062/nxp/evkmimxrt1060_debug.ld -Xlinker --gc-sections -lm
