version: 2

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

build:
  image: latest
  apt_packages:
    - libusb-1.0.0-dev

python:
  version: 3.7
  install:
    - requirements: software/requirements.txt
    - method: setuptools
      path: .

submodules:
  include:
    - tutorials
  recursive: true
