VPATH += :$(HALPATH)/sam4l
SRC += startup_sam4l.c sam4l_hal.c hwaes.c  uart.c
EXTRAINCDIRS += $(HALPATH)/sam4l $(HALPATH)/sam4l/asf/sam4l4/include $(HALPATH)/saml11/CMSIS

MCU_FLAGS = -mcpu=cortex-m4

CC = arm-none-eabi-gcc
OBJCOPY = arm-none-eabi-objcopy
OBJDUMP = arm-none-eabi-objdump
SIZE = arm-none-eabi-size
AR = arm-none-eabi-ar rcs
NM = arm-none-eabi-nm

#Output Format = Binary for this target
FORMAT = binary

CFLAGS += -fdata-sections -ffunction-sections -mthumb -mlong-calls -mfloat-abi=soft
CPPFLAGS += $(CFLAGS)
ASFLAGS += -mthumb -mfloat-abi=soft

CDEFS += -D__ATSAM4LC2A__
CPPDEFS += $(CDEFS)

LDFLAGS += -specs=nano.specs -specs=nosys.specs -T $(HALPATH)/sam4l/sam4lc2a_flash.ld -Wl,--gc-sections -lm
