TARGET = ChipWhisperer-Nano

SRC += cwnano_adc.c cwnano_glitch.c main.c naeusb_nano.c 
SRC += naeusb/circbuffer.c naeusb/naeusb_default.c naeusb/naeusb_mpsse.c naeusb/naeusb_usart.c
SRC += naeusb/naeusb.c naeusb/udc.c

LINKERFILE = naeusb/flash_sam4s.ld

include naeusb/makefile.cw