/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* LED1 */
#define LED1_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED1_0_INBUF_ENABLED 0u
#define LED1_0_INIT_DRIVESTATE 1u
#define LED1_0_INIT_MUXSEL 0u
#define LED1_0_INPUT_SYNC 2u
#define LED1_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED1_0_NUM 3u
#define LED1_0_PORT GPIO_PRT6
#define LED1_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED1_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED1_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED1_INBUF_ENABLED 0u
#define LED1_INIT_DRIVESTATE 1u
#define LED1_INIT_MUXSEL 0u
#define LED1_INPUT_SYNC 2u
#define LED1_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED1_NUM 3u
#define LED1_PORT GPIO_PRT6
#define LED1_SLEWRATE CY_GPIO_SLEW_FAST
#define LED1_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* LED2 */
#define LED2_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED2_0_INBUF_ENABLED 0u
#define LED2_0_INIT_DRIVESTATE 1u
#define LED2_0_INIT_MUXSEL 0u
#define LED2_0_INPUT_SYNC 2u
#define LED2_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED2_0_NUM 2u
#define LED2_0_PORT GPIO_PRT6
#define LED2_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED2_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED2_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED2_INBUF_ENABLED 0u
#define LED2_INIT_DRIVESTATE 1u
#define LED2_INIT_MUXSEL 0u
#define LED2_INPUT_SYNC 2u
#define LED2_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED2_NUM 2u
#define LED2_PORT GPIO_PRT6
#define LED2_SLEWRATE CY_GPIO_SLEW_FAST
#define LED2_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* LED3 */
#define LED3_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED3_0_INBUF_ENABLED 0u
#define LED3_0_INIT_DRIVESTATE 1u
#define LED3_0_INIT_MUXSEL 0u
#define LED3_0_INPUT_SYNC 2u
#define LED3_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED3_0_NUM 1u
#define LED3_0_PORT GPIO_PRT6
#define LED3_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED3_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED3_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED3_INBUF_ENABLED 0u
#define LED3_INIT_DRIVESTATE 1u
#define LED3_INIT_MUXSEL 0u
#define LED3_INPUT_SYNC 2u
#define LED3_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED3_NUM 1u
#define LED3_PORT GPIO_PRT6
#define LED3_SLEWRATE CY_GPIO_SLEW_FAST
#define LED3_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_rx */
#define UART_rx_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_rx_0_INBUF_ENABLED 1u
#define UART_rx_0_INIT_DRIVESTATE 1u
#define UART_rx_0_INIT_MUXSEL 18u
#define UART_rx_0_INPUT_SYNC 2u
#define UART_rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_rx_0_NUM 0u
#define UART_rx_0_PORT GPIO_PRT5
#define UART_rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_rx_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_rx_INBUF_ENABLED 1u
#define UART_rx_INIT_DRIVESTATE 1u
#define UART_rx_INIT_MUXSEL 18u
#define UART_rx_INPUT_SYNC 2u
#define UART_rx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_rx_NUM 0u
#define UART_rx_PORT GPIO_PRT5
#define UART_rx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_rx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_tx */
#define UART_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_tx_0_INBUF_ENABLED 0u
#define UART_tx_0_INIT_DRIVESTATE 1u
#define UART_tx_0_INIT_MUXSEL 18u
#define UART_tx_0_INPUT_SYNC 2u
#define UART_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_tx_0_NUM 1u
#define UART_tx_0_PORT GPIO_PRT5
#define UART_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_tx_INBUF_ENABLED 0u
#define UART_tx_INIT_DRIVESTATE 1u
#define UART_tx_INIT_MUXSEL 18u
#define UART_tx_INPUT_SYNC 2u
#define UART_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_tx_NUM 1u
#define UART_tx_PORT GPIO_PRT5
#define UART_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Pin_Switch */
#define Pin_Switch_0_DRIVEMODE CY_GPIO_DM_PULLUP
#define Pin_Switch_0_INBUF_ENABLED 1u
#define Pin_Switch_0_INIT_DRIVESTATE 1u
#define Pin_Switch_0_INIT_MUXSEL 0u
#define Pin_Switch_0_INPUT_SYNC 2u
#define Pin_Switch_0_INTERRUPT_MODE CY_GPIO_INTR_FALLING
#define Pin_Switch_0_NUM 1u
#define Pin_Switch_0_PORT GPIO_PRT0
#define Pin_Switch_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_Switch_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_Switch_DRIVEMODE CY_GPIO_DM_PULLUP
#define Pin_Switch_INBUF_ENABLED 1u
#define Pin_Switch_INIT_DRIVESTATE 1u
#define Pin_Switch_INIT_MUXSEL 0u
#define Pin_Switch_INPUT_SYNC 2u
#define Pin_Switch_INTERRUPT_MODE CY_GPIO_INTR_FALLING
#define Pin_Switch_NUM 1u
#define Pin_Switch_PORT GPIO_PRT0
#define Pin_Switch_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_Switch_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Trigger_pin */
#define Trigger_pin_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Trigger_pin_0_INBUF_ENABLED 0u
#define Trigger_pin_0_INIT_DRIVESTATE 0u
#define Trigger_pin_0_INIT_MUXSEL 0u
#define Trigger_pin_0_INPUT_SYNC 2u
#define Trigger_pin_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Trigger_pin_0_NUM 3u
#define Trigger_pin_0_PORT GPIO_PRT5
#define Trigger_pin_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Trigger_pin_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Trigger_pin_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Trigger_pin_INBUF_ENABLED 0u
#define Trigger_pin_INIT_DRIVESTATE 0u
#define Trigger_pin_INIT_MUXSEL 0u
#define Trigger_pin_INPUT_SYNC 2u
#define Trigger_pin_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Trigger_pin_NUM 3u
#define Trigger_pin_PORT GPIO_PRT5
#define Trigger_pin_SLEWRATE CY_GPIO_SLEW_FAST
#define Trigger_pin_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
