#!/usr/bin/python

import ctypes
import os

from chipwhisperer.capture.ui.CWCaptureGUI import main

if __name__ == '__main__':

    # Windows work-around
    if os.name == "nt":
        myappid = u'newaetech.chipwhisperer.api.git'  # arbitrary string
        ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(myappid)

    main()
