VPATH += :$(HALPATH)/lpc55s6x :$(HALPATH)/lpc55s6x/device
SRC += lpc55s6x_hal.c startup_lpc55s69_cm33_core0.c system_LPC55S69_cm33_core0.c semihost_hardfault.c

VPATH += :$(HALPATH)/lpc55s6x/utilities
SRC += fsl_assert.c fsl_debug_console.c fsl_str.c

VPATH += :$(HALPATH)/lpc55s6x/drivers
SRC += fsl_clock.c fsl_common.c fsl_flexcomm.c fsl_gpio.c fsl_hashcrypt.c fsl_inputmux.c fsl_power.c fsl_puf.c fsl_reset.c fsl_rng.c fsl_usart.c

VPATH += :$(HALPATH)/lpc55s6x/component
SRC += fsl_generic_list.c fsl_serial_manager.c fsl_serial_port_uart.c fsl_usart_adapter.c

EXTRAINCDIRS += $(HALPATH)/lpc55s6x $(HALPATH)/lpc55s6x/CMSIS
EXTRAINCDIRS += $(HALPATH)/lpc55s6x/utilities $(HALPATH)/lpc55s6x/drivers
EXTRAINCDIRS += $(HALPATH)/lpc55s6x/device
EXTRAINCDIRS += $(HALPATH)/lpc55s6x/component

MCU_FLAGS = -mcpu=cortex-m33

CC = arm-none-eabi-gcc
OBJCOPY = arm-none-eabi-objcopy
OBJDUMP = arm-none-eabi-objdump
SIZE = arm-none-eabi-size
AR = arm-none-eabi-ar rcs
NM = arm-none-eabi-nm

#Output Format = Binary for this target
FORMAT = binary

CFLAGS += -fdata-sections -ffunction-sections -funsigned-char -funsigned-bitfields -mthumb -mlong-calls
CPPFLAGS += $(CFLAGS)
ASFLAGS += -mthumb

CDEFS += -DCPU_LPC55S69JBD100 -DCPU_LPC55S69JBD100_cm33 -DCPU_LPC55S69JBD100_cm33_core0
CPPDEFS += $(CDEFS)

LDFLAGS += --specs=nano.specs -T $(HALPATH)/lpc55s6x/lpcxpresso55s69_flashiap1_debug.ld -Wl,--gc-sections -lm
