#########################
# configuration section #
#########################

# Defines the location of the EZ-USB SDK
ZTEXPREFIX=../../../..

# ihx files (firmware ROM files) that have to be build 
IHXTARGETS=OpenADC.ihx
# Extra Dependencies for ihx files
IHXEXTRADEPS=

################################
# DO NOT CHANAGE THE FOLLOWING #
################################
# includes the main Makefile
include $(ZTEXPREFIX)/Makefile.mk
