VPATH += :$(HALPATH)/stm32f1
SRC += stm32f1_hal.c stm32f1_hal_lowlevel.c
EXTRAINCDIRS += $(HALPATH)/stm32f1 $(HALPATH)/stm32f1/CMSIS $(HALPATH)/stm32f1/CMSIS/core $(HALPATH)/stm32f1/CMSIS/device $(HALPATH)/stm32f1/Legacy

ASRC += stm32f1_startup.S

MCU_FLAGS = -mcpu=cortex-m3

CC = arm-none-eabi-gcc
OBJCOPY = arm-none-eabi-objcopy
OBJDUMP = arm-none-eabi-objdump
SIZE = arm-none-eabi-size
AR = arm-none-eabi-ar rcs
NM = arm-none-eabi-nm

#Output Format = Binary for this target
FORMAT = binary

CFLAGS +=   -mthumb -mfloat-abi=soft -ffunction-sections
CPPFLAGS += -mthumb -mfloat-abi=soft -ffunction-sections
ASFLAGS +=  -mthumb -mfloat-abi=soft -ffunction-sections

ifeq ($(MCU_CLK), INT)
  CFLAGS += -DUSE_INTERNAL_CLK
endif

CDEFS   += -DSTM32F100xB -DSTM32F1 -DSTM32 -DDEBUG
CPPDEFS += -DSTM32F100xB -DSTM32F1 -DSTM32 -DDEBUG

LDFLAGS +=  --specs=nano.specs -T $(HALPATH)/stm32f1/LinkerScript.ld -Wl,--gc-sections -lm
LDFLAGS += -mthumb -mcpu=cortex-m3