VPATH += :$(HALPATH)/sam3u1c
TMPSRC += $(wildcard $(HALPATH)/sam3u1c/*.c)
# DVRSRC += $(wildcard $(HALPATH)/sam3u1c/Drivers/*.c)
SRC += $(subst $(HALPATH)/sam3u1c/,,$(TMPSRC))
$(info SRC is $(SRC))
EXTRAINCDIRS += $(HALPATH)/sam3u1c $(HALPATH)/sam3u1c/inc $(HALPATH)/sam3u1c/inc/sam $(HALPATH)/sam3u1c/inc/sam_twi

LINKERFILE = $(HALPATH)/sam3u1c/flash.ld

MCU_FLAGS = -mcpu=cortex-m3
CC = arm-none-eabi-gcc
OBJCOPY = arm-none-eabi-objcopy
OBJDUMP = arm-none-eabi-objdump
SIZE = arm-none-eabi-size
AR = arm-none-eabi-ar rcs
NM = arm-none-eabi-nm

#Output Format = Binary for this target
FORMAT = binary
CFLAGS += -fdata-sections -ffunction-sections -mlong-calls -g3 -Wall -pipe -fno-strict-aliasing -Wall -Wstrict-prototypes -Wmissing-prototypes -Wchar-subscripts -Wcomment -Wformat=2 --param max-inline-insns-single=500

CFLAGS += -DDEBUG -D__SAM3U2E__ -DARM_MATH_CM3=true -Dprintf=iprintf -DUDD_ENABLE -Dscanf=iscanf -DPLATFORMCW1190=1

LDFLAGS += -mthumb -Wl,--start-group -L $(HALPATH)/sam3u1c/ -lm -Wl,--end-group   -T $(LINKERFILE) -Wl,--gc-sections -Wl,--entry=Reset_Handler -Wl,--cref -mthumb


# ASFLAGS += -g -DDEBUG -D__STARTUP_CLEAR_BSS -g -Wall -fno-common -ffunction-sections -fdata-sections -ffreestanding -fno-builtin
# ASFLAGS += -mthumb -mapcs -std=gnu99 -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16

# LDFLAGS += -mthumb -Xlinker --gc-sections -Xlinker -static -Xlinker -z -Xlinker muldefs -T $(LINKERFILE)
# LDFLAGS += --specs=nano.specs --specs=nosys.specs -Wl,--start-group -L $(HALPATH)/sam3u1c/ -l:lib_mmcau.a -lm -lc -lgcc -lnosys -Wl,--end-group

# LDFLAGS += -g --specs=nano.specs --specs=nosys.specs -Wall -fno-common -ffunction-sections -fdata-sections -ffreestanding -fno-builtin -mthumb -mapcs -Xlinker --gc-sections -Xlinker -static -Xlinker -z -Xlinker muldefs -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -T $(LINKERFILE) -Wl,--start-group -L $(HALPATH)/sam3u1c/ -l:lib_mmcau.a -lm -lc -lgcc -lnosys -Wl,--end-group
