VPATH += :$(HALPATH)/cc2538
#SRC += $(wildcard ./*.c)
SRC += cc2538_hal.c cpu.c debug.c gpio.c interrupt.c ioc.c sys_ctrl.c uart.c cx2538_setup.c
EXTRAINCDIRS += $(HALPATH)/cc2538

ASRC += start.S
CC = arm-none-eabi-gcc
OBJCOPY = arm-none-eabi-objcopy
OBJDUMP = arm-none-eabi-objdump
SIZE = arm-none-eabi-size
AR = arm-none-eabi-ar rcs
NM = arm-none-eabi-nm

FORMAT = binary

CFLAGS=--specs=nosys.specs -mcpu=cortex-m3 -mthumb
CPPFLAGS=--specs=nosys.specs -mcpu=cortex-m3 -mthumb
ASFLAGS=--specs=nosys.specs -mcpu=cortex-m3 -mthumb

LDFLAGS += -T $(HALPATH)/cc2538/LinkerFile.ld -lm
