VPATH += :$(HALPATH)/neorv32
SRC += neorv32_cfs.c neorv32_cpu.c neorv32_gpio.c neorv32_gptmr.c neorv32_mtime.c 
SRC += neorv32_neoled.c neorv32_pwm.c neorv32_rte.c neorv32_slink.c neorv32_spi.c 
SRC += neorv32_trng.c neorv32_twi.c neorv32_uart.c neorv32_wdt.c neorv32_xip.c neorv32_xirq.c
SRC += neorv32_hal.c
EXTRAINCDIRS += $(HALPATH)/neorv32

ASRC += crt0.S

MCU_FLAGS = -march=rv32i -mabi=ilp32 

CC = riscv64-unknown-elf-gcc
OBJCOPY = riscv64-unknown-elf-objcopy
OBJDUMP = riscv64-unknown-elf-objdump
SIZE = riscv64-unknown-elf-size
AR = riscv64-unknown-elf-ar rcs
NM = riscv64-unknown-elf-nm

#Output Format = Binary for this target
FORMAT = binary

CFLAGS += -Wall -ffunction-sections -fdata-sections -nostartfiles -mno-fdiv -Wl,--gc-sections -lm -lc -lgcc -lc
CFLAGS += -falign-functions=4 -falign-labels=4 -falign-loops=4 -falign-jumps=4
CPPFLAGS += -Wall -ffunction-sections -fdata-sections -nostartfiles -mno-fdiv -Wl,--gc-sections -lm -lc -lgcc -lc
CPPFLAGS += -falign-functions=4 -falign-labels=4 -falign-loops=4 -falign-jumps=4
ASFLAGS += -Wall -ffunction-sections -fdata-sections -nostartfiles -mno-fdiv -Wl,--gc-sections -lm -lc -lgcc -lc
ASFLAGS += -falign-functions=4 -falign-labels=4 -falign-loops=4 -falign-jumps=4

#CDEFS += -DSTM32F303xC -DSTM32F3 -DSTM32 -DDEBUG
#CPPDEFS += -DSTM32F303xC -DSTM32F3 -DSTM32 -DDEBUG

LDFLAGS += -T $(HALPATH)/neorv32/neorv32.ld