# what the final build file will be called
TARGET = simpleserial-test

# our C firmware file
SRC += test2.c

SS_VER = SS_VER_2_1

# include other required build files
include ../simpleserial/Makefile.simpleserial

FIRMWAREPATH = ../.
include $(FIRMWAREPATH)/Makefile.inc
