# Makefile for CW308T-MPC5676R Target

#Normal installation of S32 goes here:
NXPS32DSROOT = C:/NXP/S32DS_Power_v2.1

#NXPS32DSROOT = D:/devtools/NXP/S32DS_Power_v2.1

VPATH += :$(HALPATH)/mpc5676r
VPATH += :$(HALPATH)/mpc5676r/nxp
VPATH += :$(HALPATH)/mpc5676r/nxp/device
VPATH += :$(HALPATH)/mpc5676r/nxp/drivers/src/CAN
VPATH += :$(HALPATH)/mpc5676r/nxp/drivers/src/PINS/siu
#VPATH += :$(HALPATH)/mpc5676r/nxp/drivers/src/PINS/siul2
VPATH += :$(HALPATH)/mpc5676r/nxp/drivers/src/CLOCK
VPATH += :$(HALPATH)/mpc5676r/nxp/drivers/src/IRQ
VPATH += :$(HALPATH)/mpc5676r/nxp/drivers/src/SEM
VPATH += :$(HALPATH)/mpc5676r/nxp/drivers/src/ESCI
VPATH += :$(HALPATH)/mpc5676r/nxp/pal/src/UART
VPATH += :$(HALPATH)/mpc5676r/nxp/source
VPATH += :$(HALPATH)/mpc5676r/nxp/osif
VPATH += :$(HALPATH)/mpc5676r/nxp/startup
VPATH += :$(HALPATH)/mpc5676r/nxp/util
VPATH += :$(HALPATH)/mpc5676r/nxp/config

EXTRAINCDIRS += $(HALPATH)/mpc5676r/nxp
EXTRAINCDIRS += $(HALPATH)/mpc5676r/nxp/device
EXTRAINCDIRS += $(HALPATH)/mpc5676r/nxp/drivers/src/CAN
EXTRAINCDIRS += $(HALPATH)/mpc5676r/nxp/drivers/src/PINS/siu
#EXTRAINCDIRS += $(HALPATH)/mpc5676r/nxp/drivers/src/PINS/siul2
EXTRAINCDIRS += $(HALPATH)/mpc5676r/nxp/drivers/src/SEM
EXTRAINCDIRS += $(HALPATH)/mpc5676r/nxp/drivers/src/IRQ
EXTRAINCDIRS += $(HALPATH)/mpc5676r/nxp/drivers/src/ESCI
EXTRAINCDIRS += $(HALPATH)/mpc5676r/nxp/drivers/inc
EXTRAINCDIRS += $(HALPATH)/mpc5676r/nxp/pal/src/UART
EXTRAINCDIRS += $(HALPATH)/mpc5676r/nxp/pal/inc
EXTRAINCDIRS += $(HALPATH)/mpc5676r/nxp/source
EXTRAINCDIRS += $(HALPATH)/mpc5676r/nxp/startup
EXTRAINCDIRS += $(HALPATH)/mpc5676r/nxp/osif
EXTRAINCDIRS += $(HALPATH)/mpc5676r/nxp/util

EXTRAINCDIRS += $(NXPS32DSROOT)/S32DS/build_tools/e200_ewl2/EWL_C/include
EXTRAINCDIRS += $(NXPS32DSROOT)/S32DS/build_tools/e200_ewl2/EWL_C/include/pa

ASRC += startup_MPC5676R.S intc_sw_handlers.S
SRC += MPC5676R_hwinit.c MPC5676R_intrinit.c
SRC += sema42_driver.c
SRC += osif_baremetal.c
SRC += flexcan_driver.c flexcan_hw_access.c flexcan_irq.c
SRC += pins_siu_driver.c siu_hw_access.c
SRC += clock_MPC5676R.c
SRC += interrupt_manager_MPC56xx.c sema42_driver.c
SRC += esci_driver.c esci_hw_access.c esci_irq.c
SRC += uart_pal.c
SRC += canCom1.c Cpu.c pin_mux.c uart_pal1.c
SRC += MPC5676R_hal.c

#TODO - should this be DCPU_MPC5676R???
MCU_FLAGS = -std=c99 -DSTART_FROM_FLASH -DCPU_MPC5777C -DTURN_ON_CPU0 -DDEV_ERROR_DETECT  -O0 -g3 -Wall -fmessage-length=0 -fstrict-volatile-bitfields -ffunction-sections -fdata-sections -mcpu=e200z7 -specs=ewl_c9x_noio.specs -mbig -mvle -mregnames -mhard-float --sysroot="$(NXPS32DSROOT)/S32DS/build_tools/e200_ewl2"

CC = powerpc-eabivle-gcc
OBJCOPY = powerpc-eabivle-objcopy
OBJDUMP = powerpc-eabivle-objdump
SIZE = powerpc-eabivle-size
AR = powerpc-eabivle-ar rcs
NM = powerpc-eabivle-nm

#Output Format = Binary for this target
FORMAT = binary

CPPFLAGS += -E
ASFLAGS +=

CPPDEFS += $(CDEFS)

#TODO - nosys.specs instead??
#TODO - removed the line '-specs=ewl_c9x_noio.specs' from this as it otherwise caused an error???
LDFLAGS += -T"$(HALPATH)\mpc5676r\nxp\56xx_flash.ld" -Wl,-Map,"simpleflexcan.map" -Xlinker --gc-sections -mcpu=e200z7  -mhard-float --sysroot="$(NXPS32DSROOT)/S32DS/build_tools/e200_ewl2"
#LDFLAGS += -specs=nosys.specs s -T $(HALPATH)/mpc5676r/nxp/MPC5676R_FLASH.lcf -Xlinker --gc-sections -lm
