# Processor frequency (external freq-in)
ifndef F_CPU
F_CPU = 7372800
endif


HALPATH = $(FIRMWAREPATH)/hal
VPATH += :$(HALPATH)

#Default stuff
EXTRAINCDIRS += $(HALPATH)

#Manually have to update this list...
define KNOWN_PLATFORMS

+--------------------------------------------------+
| PLATFORM      | DESCRIPTION                      |
+--------------------------------------------------+
| CW301_AVR     | Multi-Target Board, AVR Target   |
+--------------------------------------------------+
| CW303         | XMEGA Target (CWLite), Also works|
|               | for CW308T-XMEGA                 |
+--------------------------------------------------+
| CW304         | ATMega328P (NOTDUINO), Also works|
|               | for CW308T-AVR                   |
+--------------------------------------------------+
| CW308_MEGARF  | ATMega2564RFR2 Target for CW308T |
+--------------------------------------------------+
| CW308_SAM4L   | CW308T-SAM4L (Atmel SAM4L)       |
+--------------------------------------------------+
| CW308_STM32F4 | CW308T-STM32F4 (ST Micro STM32F4)|
+--------------------------------------------------+

endef

PLTNAME = Unknown Platform

ifeq ($(PLATFORM),CW301_AVR)
 MCU = atmega328
 HAL = avr
 PLTNAME = Multi-Target Board, AVR Target
else ifeq ($(PLATFORM),CW301_XMEGA)
 MCU = atxmega16a4
 HAL = xmega
 PLTNAME = Multi-Target Board, XMEGA Target
else ifeq ($(PLATFORM),CW303)
#d4 not officially supported, by has same reg map
 MCU = atxmega128d3
 HAL = xmega
 PLTNAME = CW-Lite XMEGA
else ifeq ($(PLATFORM),CW304)
 MCU = atmega328
 HAL = avr
 PLTNAME = CW-Lite NOTDUINO
else ifeq ($(PLATFORM),CW308_MEGARF)
 MCU = atmega128rfa1
# MCU = atmega2564rfr2
 HAL = avr
 PLTNAME = CW308T: ATMegaRF Target
else ifeq ($(PLATFORM),CW308_SAM4L)
 HAL = sam4l
 PLTNAME = CW308T: SAM4L Target
else ifeq ($(PLATFORM),CW308_STM32F4)
 HAL = stm32f4
 PLTNAME = CW308T: STM32F4 Target
else
  $(error Invalid or empty PLATFORM: $(PLATFORM). Known platforms: $(KNOWN_PLATFORMS))
  $(error haHA)
endif

include $(HALPATH)/$(HAL)/Makefile.$(HAL)

CDEFS += -DHAL_TYPE=HAL_$(HAL) -DPLATFORM=$(PLATFORM)

