# Processor frequency (external freq-in)
ifndef F_CPU
F_CPU = 7372800
endif


HALPATH = $(FIRMWAREPATH)/hal
VPATH += :$(HALPATH)

#Default stuff
EXTRAINCDIRS += $(HALPATH)

#Manually have to update these lists...
PLATFORM_LIST = CW308_CC2538 CW301_AVR CW303 CW304 CW308_MEGARF CW308_SAM4L \
	CW308_STM32F0 CW308_STM32F1 CW308_STM32F2 CW308_STM32F3 CW308_STM32F4 CW308_K24F SAM3U1C

define KNOWN_PLATFORMS

+--------------------------------------------------+
| PLATFORM      | DESCRIPTION                      |
+--------------------------------------------------+
| CW301_AVR     | Multi-Target Board, AVR Target   |
+--------------------------------------------------+
| CW303         | XMEGA Target (CWLite), Also works|
|               | for CW308T-XMEGA                 |
+--------------------------------------------------+
| CW304         | ATMega328P (NOTDUINO), Also works|
|               | for CW308T-AVR                   |
+--------------------------------------------------+
| CW308_MEGARF  | ATMega2564RFR2 Target for CW308T |
+--------------------------------------------------+
| CW308_SAM4L   | CW308T-SAM4L (Atmel SAM4L)       |
+--------------------------------------------------+
| CW308_STM32F0 | CW308T-STM32F0 (ST Micro STM32F0)|
+--------------------------------------------------+
| CW308_STM32F1 | CW308T-STM32F0 (ST Micro STM32F1)|
+--------------------------------------------------+
| CW308_STM32F2 | CW308T-STM32F2 (ST Micro STM32F2)|
+--------------------------------------------------+
| CW308_STM32F3 | CW308T-STM32F3 (ST Micro STM32F3)|
+--------------------------------------------------+
| CW308_STM32F4 | CW308T-STM32F4 (ST Micro STM32F4)|
+--------------------------------------------------+
| CW308_CC2538  | CW308-CC2538 (TI CC2538)         |
+--------------------------------------------------+
| CW308_K24F    | CW308-K24F (NXP Kinetis K24F     |
+--------------------------------------------------+

Options to define platform:
(1) Run make with PLATFORM specified as follows:
make PLATFORM=CW304

(2) Save a file called Makefile.platform with contents:
PLATFORM=CW304

endef

PLTNAME = Unknown Platform

ifeq ($(DEMO),SECCAN)
	CFLAGS += -DSECCAN
endif

ifeq ($(PLATFORM),CW301_AVR)
 MCU = atmega328
 HAL = avr
 PLTNAME = Multi-Target Board, AVR Target
else ifeq ($(PLATFORM),CW301_XMEGA)
 MCU = atxmega16a4
 HAL = xmega
 PLTNAME = Multi-Target Board, XMEGA Target
else ifeq ($(PLATFORM),CWAVRCAN)
 MCU = at90can128
 HAL = avr
 PLTNAME = AT90CAN128 Target
else ifeq ($(PLATFORM),CW303)
#d4 not officially supported, by has same reg map
 MCU = atxmega128d3
 HAL = xmega
 PLTNAME = CW-Lite XMEGA
else ifeq ($(PLATFORM),CW304)
 MCU = atmega328
 HAL = avr
 PLTNAME = CW-Lite NOTDUINO
else ifeq ($(PLATFORM),CW308_MEGARF)
 MCU = atmega128rfa1
# MCU = atmega2564rfr2
 HAL = avr
 PLTNAME = CW308T: ATMegaRF Target
else ifeq ($(PLATFORM),CW308_SAM4L)
 HAL = sam4l
 PLTNAME = CW308T: SAM4L Target
else ifeq ($(PLATFORM),CW308_STM32F0)
 HAL = stm32f0
 PLTNAME = CW308T: STM32F0 Target
else ifeq ($(PLATFORM),CW308_STM32F1)
 HAL = stm32f1
 PLTNAME = CW308T: STM32F1 Target
else ifeq ($(PLATFORM),CW308_STM32F2)
 HAL = stm32f2
 PLTNAME = CW308T: STM32F2 Target
else ifeq ($(PLATFORM),CW308_STM32F3)
 HAL = stm32f3
 PLTNAME = CW308T: STM32F3 Target
else ifeq ($(PLATFORM),CW308_STM32F4)
 HAL = stm32f4
 PLTNAME = CW308T: STM32F4 Target
else ifeq ($(PLATFORM),CW308_CC2538)
 HAL = cc2538
 PLTNAME = cc2538 Target
else ifeq ($(PLATFORM),CW308_K24F)
 HAL = k24f
 PLTNAME = k24f Target
else ifeq ($(PLATFORM),SAM3U1C)
	HAL = sam3u1c
	PLTNAME = sam3u1c
else
  $(error Invalid or empty PLATFORM: $(PLATFORM). Known platforms: $(KNOWN_PLATFORMS))
  $(error haHA)
endif

include $(HALPATH)/$(HAL)/Makefile.$(HAL)

CDEFS += -DHAL_TYPE=HAL_$(HAL) -DPLATFORM=$(PLATFORM)

