VPATH += :$(HALPATH)/stm32f3
SRC += stm32f3_hal.c stm32f3_hal_lowlevel.c stm32f3_sysmem.c
EXTRAINCDIRS += $(HALPATH)/stm32f3 $(HALPATH)/stm32f3/CMSIS $(HALPATH)/stm32f3/CMSIS/core $(HALPATH)/stm32f3/CMSIS/device $(HALPATH)/stm32f4/Legacy

ifeq ($(DEMO),SECCAN)
	SRC += stm32f3_hal_seccan.c stm32f3xx_hal_adc_ex.c stm32f3xx_hal_tim.c stm32f3xx_hal_can.c
endif

ASRC += stm32f3_startup.S

MCU_FLAGS = -mcpu=cortex-m4

CC = arm-none-eabi-gcc
CXX = arm-none-eabi-g++
OBJCOPY = arm-none-eabi-objcopy
OBJDUMP = arm-none-eabi-objdump
SIZE = arm-none-eabi-size
AR = arm-none-eabi-ar rcs
NM = arm-none-eabi-nm

ifeq ($(MCU_CLK), INT)
  CFLAGS += -DUSE_INTERNAL_CLK
endif

#Output Format = Binary for this target
FORMAT = binary

CFLAGS += -mthumb -mfloat-abi=soft -fmessage-length=0 -ffunction-sections
CPPFLAGS += -mthumb -mfloat-abi=soft -fmessage-length=0 -ffunction-sections
ASFLAGS += -mthumb -mfloat-abi=soft -fmessage-length=0 -ffunction-sections

CDEFS += -DSTM32F303xC -DSTM32F3 -DSTM32 -DDEBUG
CPPDEFS += -DSTM32F303xC -DSTM32F3 -DSTM32 -DDEBUG

LDFLAGS += --specs=nano.specs --specs=nosys.specs -T $(HALPATH)/stm32f3/LinkerScript.ld -Wl,--gc-sections -lm