#!/bin/bash -x

set -e

if [ "$#" -ne 7 ]; then
  echo "Illegal number of parameters" >&2
  exit 1
fi

host=$1
machine_name=$2
machine_header=$3
machine_inline=$4
platform_header=$5
machine_ldscript=$6
install_dir=$7

machine_header=$(pwd)/$machine_header
machine_inline=$(pwd)/$machine_inline
platform_header=$(pwd)/$platform_header
machine_ldscript=$(pwd)/$machine_ldscript
install_dir=$(pwd)/${install_dir}

export RISCV_PATH=$RISCV

autoreconf -i
./configure \
  --host=$host \
  --disable-maintainer-mode \
  --with-preconfigured \
  --with-machine-inline \
  --with-platform-header \
  --with-machine-name=$machine_name \
  --with-machine-header=$machine_header \
  --with-machine-inline=$machine_inline \
  --with-platform-header=$platform_header \
  --with-machine-ldscript=$machine_ldscript \
  --with-builtin-libgloss \
  --prefix=
make \
  RANLIB="riscv64-unknown-elf-ranlib -D" \
  ARFLAGS=Dcr
make  \
  RANLIB="riscv64-unknown-elf-ranlib -D" \
  ARFLAGS=Dcr \
  DESTDIR=$install_dir \
  install
